### ISSUE TITLE
Is it possible to classify vary-size image?

### ISSUE THREAD

**Issue by newforrestgump001** [dlibml/dnn#4]
I have vary-size images, it is possible to classify them without resizing them to same size. Thank you a lot!

**Comment by arrufat** [comment]
Yes, but you need a neural network that does not have some size requirements (e.g. a fully connected layer without some global pooling before it, or an `inpit_rgb_image_sized` layer).

If that is the case, then you can infer any size you want (as long as it fits on memory).
That being said, if you use varying sized images, you can't infer them by batches, you have to do it one by one.
Moreover, the network was probably trained with a particular size in mind (plus some data augmentation) so if your images differ too much from the original training set, you'll experience a drop in performance.

**Comment by newforrestgump001** [comment]
@arrufat Sincerely thank for your quick reply. Does dlib dnn module support 3d-cnn, for example, used for video classification?

**Comment by arrufat** [comment]
No, it doesn't.

**Comment by newforrestgump001** [comment]
@arrufat I got it, Thank you ~~

**Comment by newforrestgump001** [comment]
@arrufat Sorry to interrupt you. It is possible to replace svm classifier with one-class svm in self supervised demo (examples/dnn_self_supervised_learning_ex.cpp) in dlib. If possible, I want to try anomaly detection.

**Comment by arrufat** [comment]
I guess so, right away, I can't see why you couldn't do it.

**Comment by newforrestgump001** [comment]
Got it. Thank you!
